### ISSUE TITLE
Idea: Setup backup script as daily job

### ISSUE THREAD

**Issue by andys8** [purescript/pursuit-backups#3]
Hi :) I noticed the latest commit to this repository is 5 months old. Is it possible to setup a job to regularly run the [backup script](https://github.com/purescript/pursuit/blob/master/backup/backup.sh) (which I guess is used to fill this repo)?

Then this repository could be used as some kind of daily updated static database for e.g. https://github.com/purescript/package-sets/issues/6

Because as far as I am aware there is currently [no pursuit api](https://github.com/purescript/pursuit/issues/180) and the package files are not exposed.

Let me know if I can help and contribute.

**Comment by hdgarrood** [comment]
Yes, that was actually my plan and I never quite got around to it. We do have a script: https://github.com/purescript/pursuit/blob/master/backup/backup.sh it's just not set up on the server yet.

**Comment by hdgarrood** [comment]
I've just set this up, so you can expect to see updates from now on. Sorry I wasn't able to find a way to let you contribute, but since most of the work here was just poking around on the server, I couldn't see a good way to do that. Thanks for the reminder!

**Comment by andys8** [comment]
Thanks a lot 😊
